---
region: us-east-1
metrics:
- aws_namespace: AWS/EBS
  aws_metric_name: VolumeReadBytes
  aws_dimensions: [VolumeId]
  aws_dimension_select:
    VolumeId: [vol-035faf9767706322e]
  aws_statistics: [Maximum]
  range_seconds: 86400
- aws_namespace: AWS/ELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_dimension_select:
    LoadBalancerName: [myLB]
  aws_statistics: [Sum]
  range_seconds: 86400
